ARGS=-O3 -pthread -Wall -Wno-unused-function
# ARGS=-g -D_DEBUG -Wall -Wall -Wno-unused-function

CC=g++
SRC=substance.o
OBJ_LIBS= parser.a runtime.a
PARSER_PATH=parser
RUNTIME_PATH=runtime
EXE=subsc

$(EXE): $(SRC) $(OBJ_LIBS)
	$(CC) -m32 -o $(EXE) $(SRC) $(OBJ_LIBS) 
#	$(CC) -m32 -o $(EXE) $(SRC) $(OBJ_LIBS) 

parser.a:
	cd $(PARSER_PATH); make	
	
runtime.a:
	cd $(RUNTIME_PATH); make	
	
%.o: %.cpp
	$(CC) -m32 $(ARGS) -c $< 

clean:
	cd $(PARSER_PATH); make clean
	cd $(RUNTIME_PATH); make clean
	rm -f $(EXE).exe $(EXE) *.exe *.o *~

