# ARGS=-O3 -D_X64 -pthread -Wall -Wno-unused-function
ARGS=-g -D_DEBUG -D_X64 -Wall -Wall -Wno-unused-function

CC=g++
SRC=classes.o parser.o scanner.o tree.o emitter.o runtime.o substance.o 
EXE=sub

$(EXE): $(SRC)
	$(CC) -m64 -std=c++0x -o $(EXE) $(SRC) $(OBJ_LIBS) 
#	$(CC) -m64 -o $(EXE) $(SRC) $(OBJ_LIBS) 

%.o: %.cpp
	$(CC) -m64 -std=c++0x $(ARGS) -c $< 

clean:
	rm -f $(EXE).exe $(EXE) *.exe *.a *.o *~

