ARGS=-g -D_DEBUG  -Wunused -Wall -Wno-unused-function
# ARGS=-O3 -Wall -Wno-unused-function -Wno-unused-function

CC=g++
AR=ar
VPATH=jit/ia32
SRC=classes.o runtime.o jit_ia32.o
LIB=../runtime.a

$(LIB): $(SRC) $(OBJ_LIBS)
	$(AR) -cvq $(LIB) $(SRC)

%.o: %.cpp
	$(CC) -m32 $(ARGS) -c $< 

clean:
	rm -f *.o *~ $(LIB)
